### ISSUE TITLE
Resize (and possibly other commands) fails

### ISSUE THREAD

**Issue by jasonmorganson** [JasonJanelle/rscurl#2]
Attempting a server resize fails with:
An unknown error has occured. ()

The rackspace server responds with an HTTP 400 code, which when looking deeper says "{"badRequest":{"message":"Expecting well-formed JSON", in the body.

The problem it seem is that the flavorId is value is not populated. 

If I change the following code 
    RSPOST="{\"resize\":{\"flavorId\":$4}}"
to
    RSPOST="{\"resize\":{\"flavorId\":$RSFLAVORID}}"

then it works as expected.

Is there a reason you are not using the defined variables?

**Comment by JasonJanelle** [comment]
It looks like I've got a typo at line 435 and 451 where $RRIMAGEID and $RRFLAVORID should be $RSIMAGEID and $RSFLAVORID.  The functions use the data passed to them so that if those variables change the minimum number of modifications would have to be made.  It also makes the functions more portable.  

I will update and upload the fix.

**Comment by jasonmorganson** [comment]
Ah, i see it now. Good eyes.
